import './globals.css';

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	const currentYear = new Date().getFullYear();
	return (
		<html lang="en">
			<body>
				{children}
				<footer>All rights reserved © {currentYear} </footer>
			</body>
		</html>
	);
}
