import { Inter } from "next/font/google";
import "./globals.css";
import StoryblokProvider from "@/components/StoryblokProvider";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const currentYear = new Date().getFullYear();
  return (
    <StoryblokProvider>
      <html lang="en">
        <body className={`${inter.variable}`}>
          {children}
          <footer>All rights reserved © {currentYear} </footer>
        </body>
      </html>
    </StoryblokProvider>
  );
}
